name: notebook
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0

environment:
  flutter: 3.35.4
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 6.1.5+1
  shared_preferences: 2.5.3
  typicons_flutter: ^0.5.0
  rflutter_alert: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#d5d6d8"
  image: assets/splash_screen.png
  android: true
  ios: true
  android12: true

flutter:

  uses-material-design: true
